---
- name: Install Java and Cassandra on Ubuntu
  hosts: all
  become: yes
  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install OpenJDK 8
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Add Cassandra repository
      lineinfile:
        path: /etc/apt/sources.list.d/cassandra.sources.list
        line: "deb https://debian.cassandra.apache.org 41x main"
        state: present

    - name: Import Cassandra repository signing key
      apt_key:
        url: https://downloads.apache.org/cassandra/KEYS
        state: present

    - name: Update apt package list again after adding repo
      apt:
        update_cache: yes

    - name: Install Cassandra
      apt:
        name: cassandra
        state: present

    - name: Start Cassandra service
      systemd:
        name: cassandra
        state: started
        enabled: yes

    - name: Check status of Cassandra service
      systemd:
        name: cassandra
        state: started
